### PR TITLE
Black and isort diff plugins

### PR DESCRIPTION
**Pull request by rows-s**
Added smart plugins to use with `black --check --diff` and `isort --check-only --diff`.

# How to test it

```bash
mkdir linthell_black_isort_diff_test && cd $_ && git init
python3 -m venv venv && . venv/bin/activate
python -m pip install --no-cache black isort pre-commit 'linthell @ git+https://github.com/discrimy/linthell.git@0c4fdfe416369757a398f1d4ac7c737f3efd1306'
touch t.py linthell_black_baseline.txt linthell_isort_baseline.txt .pre-commit-config.yaml
git add t.py && git commit -m "init commit"
```

Add broken code to t.py:

```python
import b
import a
from _ import b, a

def func(arg,):
    pass

```
Add `pre-commit` config:

```yaml
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort --check-only --diff 
        types:  [python]
  - repo: local
    hooks:
      - id: linthell_isort
        name: linthell over isort
        language: system
        entry: linthell pre-commit lint -p isort-diff -b linthell_isort_baseline.txt --linter-command "isort --check-only --diff"
        types:  [python]
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black --check --diff
        types:  [python]
  - repo: local
    hooks:
      - id: linthell_black
        name: linthell over black
        language: system
        entry: linthell pre-commit lint -p black-diff -b linthell_black_baseline.txt --linter-command "black --check --diff"
        types:  [python]
```

run `pre-commit run --all` to see difference in outputs:
```text
isort....................................................................Failed
- hook id: isort
- exit code: 1

ERROR: /home/rows/py_dev/linthell_black_isort_diff_test/t.py Imports are incorrectly sorted and/or formatted.
--- /home/rows/py_dev/linthell_black_isort_diff_test/t.py:before        2023-08-28 19:27:10.545735
+++ /home/rows/py_dev/linthell_black_isort_diff_test/t.py:after 2023-08-28 19:27:24.559449
@@ -1,6 +1,7 @@
+import a
 import b
-import a
-from _ import b, a
+from _ import a, b
+
 
 def func(arg,):
     pass

linthell over isort......................................................Failed
- hook id: linthell_isort
- exit code: 1

t.py:1: +import a
t.py:2: -import a
t.py:3: -from _ import b, a
t.py:3: +from _ import a, b
t.py:4: +

black....................................................................Failed
- hook id: black
- exit code: 1

--- t.py        2023-08-28 16:27:10.545735+00:00
+++ t.py        2023-08-28 16:27:24.972181+00:00
@@ -1,6 +1,9 @@
 import b
 import a
 from _ import b, a
 
-def func(arg,):
+
+def func(
+    arg,
+):
     pass
would reformat t.py

Oh no! 💥 💔 💥
1 file would be reformatted.

linthell over black......................................................Failed
- hook id: linthell_black
- exit code: 1

t.py:5: -def func(arg,):
t.py:5: +
t.py:6: +def func(
t.py:7: +    arg,
t.py:8: +):
```

build `baselines`:
```bash
linthell pre-commit baseline -b linthell_isort_baseline.txt -p isort-diff --hook-name "linthell over isort" --linter-command "isort --check-only --diff"
linthell pre-commit baseline -b linthell_black_baseline.txt -p black-diff --hook-name "linthell over black" --linter-command "black --check --diff"
```
Run linhell to check that all errors are suppressed:
```bash
pre-commit run linthell_isort --all
pre-commit run linthell_black --all
```
Check baselines:
```python
# isort
t.py:+
t.py:+from _ import a, b
t.py:+import a
t.py:-from _ import b, a
t.py:-import a
# black
t.py:+
t.py:+    arg,
t.py:+):
t.py:+def func(
t.py:-def func(arg,):
```

# Code duplicate

Both Plugins has the same implementation with only different names and doc-strings, it would be fair to ask "maybe code could be reused?", but i was trying to prepare for cases when only one plugin will change the structure of output and than `linthell` will forced to adapt for new rules. If `linthell` would face it with both plugins reuses "base" code it would be a mess with `if-statements` or inheritance. Cognitive and maintain complexities would be increased significantly, and don't forget that plugin interfaced may be reused in other external plugins so `linthell` would try to make only backward-compatible changes.

### CODE REVIEW

**Comment by discrimy** [comment]
Merge fresh master, changes are messed up with the previous PR and hard to review

**Comment by discrimy** [comment]
> Both Plugins has the same implementation with only different names and doc-strings

I think it's because their output is git-diff-like, at least `git diff` prints similar output. But I agree they're similar, not equal, so it would be better to keep them seperate, or at least make common implementation of parsing git-diff-like outputs private

**Comment by discrimy** [comment]
> Check baselines:

File paths must be relative to project root and be Posix only, so they work on others' machine and on Windows too

**Comment by rows-s** [comment]
> @discrimy File paths must be relative to project root and be Posix only, so they work on others' machine and on Windows too

Added code that makes files relative for current dir. Only for isort plugin. [commit](https://github.com/discrimy/linthell/pull/23/commits/b8842b260fbeb2ea6e37957c00d2381e8e18f937)

**Comment by discrimy** [comment]
> Added code that makes files relative for working dir. Only for isort plugin. [commit](https://github.com/discrimy/linthell/pull/23/commits/b8842b260fbeb2ea6e37957c00d2381e8e18f937) Updated PR description.

Does it handles Windows paths too? Paths must be POSIX only, so you need to normalize it. For example, regex plugin does it by using `pathlib.Path` module (`Path(path).as_posix()`), I suggest to use it to work with paths. Everything else is OK.

**Comment by rows-s** [comment]
Fixed in [commit](https://github.com/discrimy/linthell/pull/23/commits/0c4fdfe416369757a398f1d4ac7c737f3efd1306).

BTW, seems like `LinthellBlackCheckPlugin` has the same issue keeping initial file path that would be different on Windows and *unix.

**Comment by discrimy** [comment]
> BTW, seems like LinthellBlackCheckPlugin has the same issue keeping initial file path that would be different on Windows and *unix.

I'll fix it later

**Pull request merged**
